# 该文件为基础页面配置
-
  path: demo
  name: 组件demo展示
  icon: dropbox
  children:
    -
      path: code
      name: 代码编辑器
      component: demo/code
    -
      path: md
      name: md编辑器
      component: demo/md
    -
      path: rich
      name: 富文本编辑器
      component: demo/rich
    -
      path: date
      component: demo/date

-
  path: dashboard
  name: Dashboard
  icon: dashboard
  component: dashboard/index
-
  path: user
  children:
    -
      path: login
      model: [user]
      component: user/login
-
  path: exception
  children:
    -
      path: 403
      component: exception/index
    -
      path: 404
      component: exception/index
    -
      path: 500
      component: exception/index
